primaryBranch: main
releaseType: ruby
handleGHRelease: true
changelogType: github
branches:
  - branch: production
    releaseType: ruby
    handleGHRelease: true
    changelogType: github
    versionFile: app/version.rb
