name: Lint, Test and Release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-lint-test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: exit 0

    - name: Lint
      run: exit 0

    - name: Test
      run: exit 0

    - name: Login to Docker Hub
      if: github.ref_name == 'main'
      uses: docker/login-action@v1
      with:
        username: johnallen3d
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      if: github.ref_name == 'main'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: johnallen3d/hello-world:latest

    - name: Deploy to Staging
      if: github.ref_name == 'main'
      run: ./bin/release
      env:
        DEPLOY_ENV: stage
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
