name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release Mock
      if: github.event.pull_request.merged == true && github.head_ref == 'release-please--branches--main'
      run: echo 'release would run now!'

