name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && env.GITHUB_HEAD_REF == 'release-please--branches--main'
    steps:
    - name: Release Mock
      run: env

