name: Release to Production

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      if: github.event.pull_request.merged == true && github.head_ref == 'release-please--branches--main'
      uses: docker/login-action@v1
      with:
        username: johnallen3d
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Production
      if: github.event.pull_request.merged == true && github.head_ref == 'release-please--branches--main'
      run: ./bin/release
      env:
        DEPLOY_ENV: prod
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
