name: Tag Release Image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: johnallen3d
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag `latest` with Current Version
        run: |
          base_image=johnallen3d/hello-world
          source_image="${base_image}:latest"
          target_image="${base_image}:${{ github.ref_name }}"

          docker pull "${source_image}"
          docker tag "${source_image}" "${target_image}"
          docker push "${target_image}"

